version: 0.0
os: linux

files:
  # Specify the source and destination for your application files
  - source: / # Deploy everything from the root of the repository
    destination: /home/ec2-user/my-app

hooks:
  # Define lifecycle events with scripts to run during the deployment
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: ec2-user

  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: ec2-user

  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 300
      runas: ec2-user
