version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "Installing dependencies..."
      - echo "EU Builspec..."
      - cd MyJavaProject/src  
      - mvn install
  build:
    commands:
      - echo "Building the JAR file..."
      - mvn clean package 
      - ls -l target


artifacts:
  files:
    - my-java-project-1.0-SNAPSHOT.jar
  base-directory: MyJavaProject/src/target
  s3-prefix: build_$(date +%Y-%m-%d)
  discard-paths: yes
  name: EU_Jar


