version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk11
    commands:
      - echo "Installing dependencies..."
      - echo "EU Builspec..."
      - mvn install

  build:
    commands:
      - echo "Building the JAR file..."
      - mvn clean package 

artifacts:
  files:
    - target/my-java-project-1.0-SNAPSHOT.jar  


