version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "Installing dependencies..."
      - echo "EU Builspec..."
      - cd MyJavaProject/src  
      - mvn install
  build:
    commands:
      - echo "Building the JAR file..."
      - mvn clean package 
      - ls -l target

artifacts:
  files:
    - '**/*'
  # base-directory: MyJavaProject/src/target
  name: eujars/$AWS_REGION-$(date +%Y-%m-%d) 


