version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "Installing dependencies..."
      - echo "US Builspec..."
      - cd MyJavaProject/src  
      - mvn install
  build:
    commands:
      - echo "Building the JAR file..."
      - mvn clean package 


artifacts:
  files:
    - target/my-java-project-1.0-SNAPSHOT.jar  

  s3-prefix: us-jars/  
  discard-paths: no 
  base-directory: target 
